project_id = "xqubydbsoucrwqhddodw"

[functions.setup-admin]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.regenerate-sitemap]
verify_jwt = false

[functions.seo-proxy]
verify_jwt = false